# Generated by Django 5.2.6 on 2025-11-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(blank=True, help_text='Formato: XXX.XXX.XXX-XX', max_length=14, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, help_text='Formato: (XX) XXXX-XXXX ou (XX) XXXXX-XXXX', max_length=15, null=True)),
                ('celular', models.CharField(blank=True, help_text='Formato: (XX) XXXX-XXXX ou (XX) XXXXX-XXXX', max_length=15, null=True)),
                ('cep', models.CharField(blank=True, help_text='Formato: XXXXX-XXX', max_length=9, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('uf', models.CharField(blank=True, help_text='Sigla do estado (ex: SP, RJ)', max_length=2, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
    ]
