# Generated by Django 5.2.6 on 2025-10-02 00:06

import clientes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(help_text='Formato: XXX.XXX.XXX-XX', max_length=14, unique=True, validators=[clientes.validators.validate_cpf])),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(blank=True, help_text='Formato: (XX) XXXX-XXXX ou (XX) XXXXX-XXXX', max_length=15, null=True, validators=[clientes.validators.validate_telefone])),
                ('celular', models.CharField(blank=True, help_text='Formato: (XX) XXXX-XXXX ou (XX) XXXXX-XXXX', max_length=15, null=True, validators=[clientes.validators.validate_telefone])),
                ('cep', models.CharField(blank=True, help_text='Formato: XXXXX-XXX', max_length=9, null=True, validators=[clientes.validators.validate_cep])),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('uf', models.CharField(help_text='Sigla do estado (ex: SP, RJ)', max_length=2, validators=[clientes.validators.validate_uf])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
    ]
