# Generated by Django 5.2.6 on 2025-09-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cep', models.CharField(help_text='Formato: XXXXX-XXX', max_length=9, verbose_name='CEP')),
                ('celular', models.CharField(help_text='Formato: (XX) XXXXX-XXXX', max_length=15, verbose_name='Celular')),
                ('telefone', models.CharField(blank=True, help_text='Formato: (XX) XXXX-XXXX', max_length=14, null=True, verbose_name='Telefone')),
                ('telefone_fixo', models.CharField(blank=True, help_text='Formato: (XX) XXXX-XXXX', max_length=14, null=True, verbose_name='Telefone Fixo')),
                ('endereço', models.CharField(max_length=255)),
                ('numeroCasa', models.CharField(max_length=10, verbose_name='Número da Casa')),
                ('bairro', models.CharField(max_length=100)),
                ('Cidade', models.CharField(max_length=100)),
                ('Complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('uf', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='UF')),
                ('rg', models.CharField(max_length=20, unique=True, verbose_name='RG')),
                ('cpf', models.CharField(help_text='Formato: XXX.XXX.XXX-XX', max_length=14, unique=True, verbose_name='CPF')),
                ('cargo', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=128)),
                ('nivel_acesso', models.CharField(choices=[('admin', 'Administrador'), ('user', 'Usuário')], max_length=50, verbose_name='Nível de Acesso')),
            ],
        ),
    ]
