# Generated by Django 5.2.6 on 2025-09-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Cidade',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Complemento',
            new_name='complemento',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='endereço',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='numeroCasa',
            new_name='numero_casa',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.CharField(max_length=15, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone_fixo',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone Fixo'),
        ),
    ]
