# Generated by Django 5.2.7 on 2025-11-26 00:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemvenda',
            options={'verbose_name': 'Item de Venda', 'verbose_name_plural': 'Itens de Venda'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['descricao'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ['-data_venda'], 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.RemoveField(
            model_name='itemvenda',
            name='desconto_percentual',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='desconto_percentual',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='obs',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='total_venda',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='descricao_produto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição do Produto'),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='desconto_percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desconto (%)'),
        ),
        migrations.AddField(
            model_name='venda',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='venda',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='preco_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Unitário'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vendas.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.venda', verbose_name='Venda'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_estoque',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade em Estoque'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Venda'),
        ),
    ]
