# Generated by Django 5.2.7 on 2025-11-26 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_bairro_alter_cliente_celular_and_more'),
        ('produtos', '0002_alter_produto_codigo_barras_alter_produto_descricao_and_more'),
        ('vendas', '0002_alter_itemvenda_options_alter_produto_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='produtos.produto'),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ['-data_venda']},
        ),
        migrations.RemoveField(
            model_name='itemvenda',
            name='descricao_produto',
        ),
        migrations.RemoveField(
            model_name='itemvenda',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='status',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='total',
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='desconto_percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='venda',
            name='desconto_percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='venda',
            name='total_venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.venda'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
