# Generated by Django 5.2.7 on 2025-11-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_estoque',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade em Estoque'),
        ),
    ]
